version: "3.7"

services:
  redis_bd:
    image: "redis:alpine"
    restart: always
    container_name: redis
    ports:
      - 6379:6379
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - rsdata:/data/rd

  app:
    build: .
    container_name: node
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    depends_on:
      - redis_bd

volumes:
  rsdata:
    driver: local
